apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: elastic
type: Opaque
stringData:
  ELASTICSEARCH_SERVICE_TOKEN: AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjp1UGJzN0llSVM3YTJmcXQ2eF9NWHl3
